config/routes.rb
Rails.application.routes.draw do
  get 'search/date'
  get 'search/vendor'
  get 'search/both'
  resources :search
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', :via => [:get]
  match '/signout', to: 'sessions#destroy',  :via => [:get]

   root 'home#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :name
end

app/models/trans_temp.rb
class TransTemp < ActiveRecord::Base
  attr_accessible :card_id, :vendor_id, :amount, :date
end

app/models/transact.rb
class Transact < ActiveRecord::Base
  attr_accessible :card_id,:vendor_id,:amount, :date
  def self.to_csv(x,z)
    attributes = %w{card_id vendor_id amount date}
    CSV.generate do |csv|
      csv << attributes
      if z!=0
        if x!=0
          puts where(:date=>x,:vendor_id=>z).inspect
          where(:date=>x,:vendor_id=>z).each do |y|
            csv<< y.attributes.values_at(*attributes)
          end
        else
          where(:vendor_id=>z).each do |y|
            csv<< y.attributes.values_at(*attributes)
          end
        end
      else
        if x!=0
          where(:date=>x).each do |y|
            csv<< y.attributes.values_at(*attributes)
          end
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  #has_secure_password
  before_save { |user| user.username = username.downcase }
  before_save :create_remember_token
  private
    
  def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/user_spec.rb
require 'spec_helper'
describe User do
	before do
			@user = User.new(username: "Example User",password: "foobar")
	end
	subject { @user }
	describe "remember token" do
		before { @user.save }
		its(:remember_token) {puts "BLUuuee"}
	end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  attr_accessible :name,:location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    puts "SEARCH"
    @x= Transact.order(:amount)
    respond_to do |format|
      format.html
      format.csv{send_data @x.to_csv}
    end
  end
  def date
    @date = Transact.all
    @x=201215
    @z=0
    respond_to do |format|
      format.html
      format.csv{send_data Transact.to_csv(@x,@z)}
    end
  end
  def vendor
    @date = Transact.all
    @z=2
    @x=0
    respond_to do |format|
      format.html
      format.csv{send_data Transact.to_csv(@x,@z)}
    end
  end
  def both
    @date = Transact.all
    @x=201215
    @z=1
    respond_to do |format|
      format.html
      format.csv{send_data Transact.to_csv(@x,@z)}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  #  @user=User.find(1)
  user=User.new(:username=>"fg",:password=>"sdf")
  end
  def create
    user = User.find_by_username(params[:session][:username])
    puts "ENTERED"
    Rails.logger.debug "create"
    #if user && user.authenticate(params[:session][:password])
    if user!=nil
      puts "IFF"
      sign_in user
      puts "SIGNED IN"
      redirect_to '/search'
    else
      flash.now[:error] = 'Invalid username/password combination'
      puts "ERROR"
      redirect_to '/signin'
    end
  end
  def destroy
    sign_out
    #self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    puts " SHOW"
    redirect_to "search"
  end
  def update
    #if signed_in?
    #  redirect_to "/search"
    #else
      redirect_to "/search/both"
    #end
  end
  def create
      puts "CREATE"
      @user = User.new(:username=>'sudiptod81',:password=>'sudiptod81')
      if @user.save
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        render 'new'
      end
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  def current_user=(user)
    @current_user = user
  end
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  def signed_in?
    !current_user.nil?
  end
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
hello

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link to "sample app", root path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link to "Profile", current user %></li>
                <li><%= link to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link to "Sign out", signout path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SudTrans</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/both.html.erb
<% if signed_in? %>
  <table>
    <tr>
      <th>Card_id</th>
      <th>Vendor_id</th>
      <th>Amount</th>
      <th>Date</th>
    </tr>
    <% @date.each do |post| %>
      <% if post.date == @x %>
        <% if post.vendor_id == @z %>
          <tr>
            <td><%= post.card_id %></td>
            <td><%= post.vendor_id %></td>
            <td><%= post.amount %></td>
            <td><%= post.date %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </table>
<% else %>
  Please log in
<% end %>

app/views/search/date.html.erb
<table>
  <tr>
    <th>Card_id</th>
    <th>Vendor_id</th>
    <th>Amount</th>
    <th>Date</th>
  </tr>
  <% @date.each do |post| %>       
    <% if post.date == @x %>
      <tr>
        <td><%= post.card_id %></td>
        <td><%= post.vendor_id %></td>
        <td><%= post.amount %></td>
        <td><%= post.date %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/search/index.html.erb
<% if signed_in? %>
  You have to choose whether you want to refine your search with date or vendor or both
<% else %>
  Not logged
<% end %>

app/views/search/vendor.html.erb
<table>
  <tr>
    <th>Card_id</th>
    <th>Vendor_id</th>
    <th>Amount</th>
    <th>Date</th>
  </tr>
  <% @date.each do |post| %>
    <% if post.vendor_id == @z %>
      <tr>
        <td><%= post.card_id %></td>
        <td><%= post.vendor_id %></td>
        <td><%= post.amount %></td>
        <td><%= post.date %></td>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/users/new.html.erb
<% provide(:title, "Sign in") %>
<h1>Sign in</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(:session, url: sessions_path) do |f| %>
      <%= f.label :username %>
      <%= f.text field :username %>
      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>
    </div>
</div>

app/views/users/update.html.erb
<% if signed_in? %>
   U r logged in
<% else %>
   Please LogIn
<% end %>